# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ec904c9d77f2a96f154a3432e1e5df33f885f0364f72ef5e8176b5262c51b2adc2b6e66d2d16cc52ad926750bf69e8eefb32120ac383b9951d52bfe3a739cdb

test:
  secret_key_base: 142ee539bca1da6d4daf5f3fdf6f1f2e9fdc888c8201d80e2699c486238681eb73923353d752c37517ade8ffc54541d3dc931bf7d1d376edeaf16eb8d29257b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
